import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <nav style={{backgroundColor:'pink' ,display:'flex',justifyContent:'space-around',height:'60px',color:'black',alignItems:'center'}}>
        <Link href="/">Home</Link>
        <Link href="post">post</Link>
        <Link href="Articels">Articels</Link>
      </nav>
      {children}
      </body>
    </html>
  );
}
